ACTION_READ = 0
ACTION_ADD = 1
ACTION_EDIT = 2
ACTION_DELETE = 3
ACTION_RESTORE = 4

ACTIONS_HUMAN_READABLE = {
  ACTION_READ: "Read",
  ACTION_ADD: "Add",
  ACTION_EDIT: "Edit",
  ACTION_DELETE: "Delete",
  ACTION_RESTORE: "Restore",
}

CONTEXT_CALENDAR = u'calendar'
CONTEXT_API = u'api'
CONTEXT_BOOKMARKLET = u'bookmarklet'
CONTEXT_EMAILREMINDER = u'emailreminder'